# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_param chipscope.maxJobs 5
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/it/K2_Mircroprocessor_8bit/K2_Mircroprocessor_8bit.cache/wt [current_project]
set_property parent.project_path /home/it/K2_Mircroprocessor_8bit/K2_Mircroprocessor_8bit.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty-a7-100:part0:1.1 [current_project]
set_property ip_output_repo /home/it/K2_Mircroprocessor_8bit/K2_Mircroprocessor_8bit.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  /home/it/K2_Mircroprocessor_8bit/K2_Mircroprocessor_8bit.srcs/sources_1/new/ALU.sv
  /home/it/LAB4_DSD/LAB4_DSD.srcs/sources_1/new/CLK_Dividers.sv
  /home/it/K2_Mircroprocessor_8bit/K2_Mircroprocessor_8bit.srcs/sources_1/new/Control_Logic.sv
  /home/it/LAB4_DSD/LAB4_DSD.srcs/sources_1/new/D_FF.sv
  /home/it/K2_Mircroprocessor_8bit/K2_Mircroprocessor_8bit.srcs/sources_1/new/Decoder.sv
  /home/it/K2_Mircroprocessor_8bit/K2_Mircroprocessor_8bit.srcs/sources_1/new/K2_Microprocessor.sv
  /home/it/K2_Mircroprocessor_8bit/K2_Mircroprocessor_8bit.srcs/sources_1/new/Multiplexers.sv
  /home/it/K2_Mircroprocessor_8bit/K2_Mircroprocessor_8bit.srcs/sources_1/new/Program_Counter.sv
  /home/it/K2_Mircroprocessor_8bit/K2_Mircroprocessor_8bit.srcs/sources_1/new/ROM.sv
  /home/it/K2_Mircroprocessor_8bit/K2_Mircroprocessor_8bit.srcs/sources_1/new/Register.sv
  /home/it/Downloads/task1/src/counter_n_bit.sv
  /home/it/Downloads/task1/src/decoder.sv
  /home/it/Downloads/task1/src/sev_seg_controller.sv
  /home/it/Downloads/task1/src/sev_seg_decoder.sv
  /home/it/K2_Mircroprocessor_8bit/K2_Mircroprocessor_8bit.srcs/sources_1/new/TOP_K2.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/it/Downloads/task1/src/pin-assignment.xdc
set_property used_in_implementation false [get_files /home/it/Downloads/task1/src/pin-assignment.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top TOP_K2 -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TOP_K2.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TOP_K2_utilization_synth.rpt -pb TOP_K2_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
