#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Dec 02 15:09:24 +03 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim TB_K2P_behav -key {Behavioral:sim_1:Functional:TB_K2P} -tclbatch TB_K2P.tcl -view /home/it/K2_Mircroprocessor_8bit/TB_K2P_behav.wcfg -log simulate.log"
xsim TB_K2P_behav -key {Behavioral:sim_1:Functional:TB_K2P} -tclbatch TB_K2P.tcl -view /home/it/K2_Mircroprocessor_8bit/TB_K2P_behav.wcfg -log simulate.log

